name: Fetch script's Jsdelivr cache

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch script's Jsdelivr cache
        run: |
          curl https://purge.jsdelivr.net/gh/mikupeto/warp-script/warp.sh